# What message should we broadcast when someone's birthday?
# Setting this to "" means the plugin will use the default one.

announcement-message: ""

# What sound effect should we play when broadcasting the birthday?
# Possible sounds reference: https://jd.papermc.io/paper/1.19/org/bukkit/Sound.html
# Leaving this empty or "" means no sound will be played.
# Setting this to 'default' will make the plugin to use the default one (dragon growl).
sound-effect: 'default'

# Should we show a title to online players?
# Leaving this empty or setting to '' means no title will be shown.
title-shown:

# This option will only work if the above one is NOT null.
# What subtitle should we show to online players?
# Leaving this empty or setting to '' means no subtitle will be shown.
subtitle-shown:

# This option will be ignored if "title-shown" is null
# What times configuration should we use for titles?
# Leaving this empty will make every option be 1 second.
# These are the pattern used in titles in milliseconds:
# To find the value in milliseconds just do "<value in seconds> * 1000".
# Fade in:
# Stay:
# Fade out:
times:
  - 500
  - 3000
  - 500